baseURL: https://rwithlazar.netlify.app/
title: R with Lazar
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Lazaro Alvarez
  avatar: https://i.ibb.co/KX8Qk1p/1583110250607.jpg
  description: Hi, I am a Data Scientist with a passion for sport analytics and betting.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/lazaroalva97/
    - icon: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/lazaro-alvarez-552078145/
